Create install_fix.sh
#The change of directory (cd impacket) was missing, it causes an execution error.

./portia.py 
Traceback (most recent call last):
  File "./portia.py", line 6, in <module>
    from deps.psexec import *
  File "/opt/portia/deps/psexec.py", line 26, in <module>
    from impacket.examples import logger
ImportError: No module named impacket.examples